CREATE SEQUENCE SEQ_CONTATO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE TBL_CONTATOS(

    ID_CONTATO INTEGER DEFAULT SEQ_CONTATO.NEXTVAL NOT NULL,
    NM_CONTATO VARCHAR(100) NOT NULL,
    EM_CONTATO VARCHAR(100) NOT NULL,
    DTNASC_CONTATO DATE NOT NULL

);