CREATE SEQUENCE SEQ_USUARIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE TBL_USUARIOS(
    ID_USUARIO INTEGER DEFAULT SEQ_CONTATO.NEXTVAL NOT NULL,
    NM_USUARIO VARCHAR(100) NOT NULL,
    EMAIL_USUARIO VARCHAR(100) UNIQUE NOT NULL,
    SENHA_USUARIO VARCHAR2(15) NOT NULL,
    ROLE VARCHAR2(50) DEFAULT 'USER';
);